routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('clients','ClientController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'clients';
    protected $fillable = ['firstname','lastname','email','phonenumber','address'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clients=Client::all();
        return view('view',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'firstname' => 'required|max:50',
            'lastname' => 'required|max:50',
            'email' => 'required|email|max:50',
            'phonenumber' => 'required|max:15',
            'address' => 'required|max:150'
        ]);
        Client::create($request->all());
       // return back()->with('success', 'Client added!');
        return redirect()->route('clients.index')->with('success','Client added successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        return view('edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'firstname' => 'required|max:50',
            'lastname' => 'required|max:50',
            'email' => 'required|email|max:50',
            'phonenumber' => 'required|max:15',
            'address' => 'required|max:150'
        ]);
        Client::find($id)->update($request->all());
        return redirect()->route('clients.index')->with('success','Client updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Client::find($id)->delete();
        return redirect()->route('clients.index')->with('success','Client deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/edit.blade.php
@extends('layout.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Update</div>
                    <div class="panel-body">
                        {!! Form::model($client, ['method' => 'PATCH','route' => ['clients.update', $client->id]]) !!}
                        <div class="form-group {{ $errors->has('firstname') ? 'has-error' : '' }}">
                            {!! Form::label('First Name:') !!}
                            {!! Form::text('firstname',null, ['class'=>'form-control', 'placeholder'=>'Enter Your First Name']) !!}
                            <span class="text-danger">{{ $errors->first('firstname') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('lastname') ? 'has-error' : '' }}">
                            {!! Form::label('Last Name:') !!}
                            {!! Form::text('lastname',null, ['class'=>'form-control', 'placeholder'=>'Enter Your Last Name']) !!}
                            <span class="text-danger">{{ $errors->first('lastname') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            {!! Form::label('Email:') !!}
                            {!! Form::text('email',null, ['class'=>'form-control', 'placeholder'=>'Enter Email']) !!}
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('phonenumber') ? 'has-error' : '' }}">
                            {!! Form::label('Phone Number:') !!}
                            {!! Form::text('phonenumber',null, ['class'=>'form-control', 'placeholder'=>'Enter Your Phone number']) !!}
                            <span class="text-danger">{{ $errors->first('phonenumber') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">
                            {!! Form::label('Address:') !!}
                            {!! Form::text('address',null, ['class'=>'form-control', 'placeholder'=>'Enter Your Address']) !!}
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success">Edit Client</button>
                        </div>
    {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <!--ul class="nav navbar-nav">
                        <li>
                            <a href="/home"><span class="fa-stack fa-lg pull-left"><i class="fa fa-home" aria-hidden="true"></i></span> Home</a>
                        </li>
                        <li>
                            <a href="/news"><span class="fa-stack fa-lg pull-left"><i class="fa fa-newspaper-o" aria-hidden="true"></i></span>News</a>
                        </li>
                        <li>
                            <a href="/about"><span class="fa-stack fa-lg pull-left"><i class="fa fa-buysellads" aria-hidden="true"></i></span>About</a>
                        </li>
                        <li>
                            <a href="/contact-us"><span class="fa-stack fa-lg pull-left"><i class="fa fa-envelope-open" aria-hidden="true"></i></span>Contact</a>
                        </li>
                    </ul-->
                </div>
            </div>
        </nav>
        <!---start of the side bar menu and wrapper--->
        <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
                   <!------<li> here!--->
                </ul>

            </div><!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid xyz">
                    <div class="row">
                        <div class="col-lg-12">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
            <!-- /#page-content-wrapper -->
        </div>
        <!---end of the side bar menu and wrapper--->
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/sidebar_menu.js') }}"></script>
</body>
</html>

resources/views/view.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Clients</div>
                    <div class="panel-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">
                                {{ Session::get('success') }}
                            </div>
                        @endif
                        <table width="670" class="table-responsive">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>FirstName</th>
                                <th>LastName</th>
                                <th>Email</th>
                                <th>PhoneNumber</th>
                                <th>Address</th>
                            </tr>
                            </thead>
                            <?php $i=1; ?>
                            @foreach($clients as $client)
                                <tr>
                                    <td>{{$i}}</td>
                                    <td>{{$client->firstname}}</td>
                                    <td>{{$client->lastname}}</td>
                                    <td>{{$client->email}}</td>
                                    <td>{{$client->phonenumber}}</td>
                                    <td>{{$client->address}}</td>
                                    <td><a href="{{route('clients.edit',$client->id)}}" class="btn btn-info">Edit</a></td>
                                    <td>
                                      {!! Form::open(['method'=>'DELETE','route'=>['clients.destroy',$client->id],'style'=>'display:inline'])!!}
                                        {!! Form::submit('Delete',['class'=>'btn btn-danger'])!!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                <?php $i++; ?>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection